export const IEM = [
    // KZ
    {
        id: "1",
        name: "KZ ZS10 Pro",
        price: "399900",
        bass: 4,
        mid: 3,
        treble: 3,
        linkBeli: "https://tokopedia.link/qmm40tL7Syb",
        jumlahDriver: 5,
        tipeDriver: "Hybrid",
    },
    {
        id: "2",
        name: "KZ ZSN Pro",
        price: "165000",
        bass: 4,
        mid: 2,
        treble: 4,
        linkBeli: "https://tokopedia.link/ekxHCBN7Syb",
        jumlahDriver: 2,
        tipeDriver: "Hybrid",
    },
    {
        id: "3",
        name: "KZ DQ6",
        price: "269000",
        bass: 4,
        mid: 2,
        treble: 4,
        linkBeli: "https://tokopedia.link/3A6cWUO7Syb",
        jumlahDriver: 3,
        tipeDriver: "Dynamic",
    },
    {
        id: "4",
        name: "KZ CRN / ZEX Pro",
        price: "259000",
        bass: 3,
        mid: 3,
        treble: 3,
        linkBeli: "https://tokopedia.link/geXiTsX7Syb",
        jumlahDriver: 3,
        tipeDriver: "Hybrid",
    },
    {
        id: "5",
        name: "KZ EDX Pro",
        price: "79000",
        bass: 5,
        mid: 2,
        treble: 3,
        linkBeli: "https://tokopedia.link/WtC6ZRZ7Syb",
        jumlahDriver: 1,
        tipeDriver: "Dynamic",
    },

    // Moondrop
    {
        id: "6",
        name: "Moondrop Chu",
        price: "279000",
        bass: 3,
        mid: 4,
        treble: 4,
        linkBeli: "https://tokopedia.link/PI3Fbe47Syb",
        jumlahDriver: 1,
        tipeDriver: "Dynamic",
    },
    {
        id: "7",
        name: "Moondrop Starfield",
        price: "1650000",
        bass: 4,
        mid: 3,
        treble: 2,
        linkBeli: "https://tokopedia.link/6qeQAZ67Syb",
        jumlahDriver: 1,
        tipeDriver: "Dynamic",
    },
    {
        id: "8",
        name: "Moondrop Aria",
        price: "1150000",
        bass: 4,
        mid: 3,
        treble: 2,
        linkBeli: "https://tokopedia.link/1FQfXy87Syb",
        jumlahDriver: 1,
        tipeDriver: "Dynamic",
    },
    {
        id: "9",
        name: "Moondrop SSR",
        price: "600000",
        bass: 1,
        mid: 3,
        treble: 5,
        linkBeli: "https://tokopedia.link/DcJu2ka8Syb",
        jumlahDriver: 1,
        tipeDriver: "Dynamic",
    },
    {
        id: "10",
        name: "Moondrop Blessing 2",
        price: "4600000",
        bass: 3,
        mid: 3,
        treble: 4,
        linkBeli: "https://tokopedia.link/SkGpWrc8Syb",
        jumlahDriver: 5,
        tipeDriver: "Hybrid",
    },
    {
        id: "11",
        name: "Moondrop KATO",
        price: "2700000",
        bass: 4,
        mid: 3,
        treble: 4,
        linkBeli: "https://tokopedia.link/UySvUBe8Syb",
        jumlahDriver: 1,
        tipeDriver: "Dynamic",
    },
    {
        id: "12",
        name: "Moondrop Quarks",
        price: "175000",
        bass: 3,
        mid: 4,
        treble: 2,
        linkBeli: "https://tokopedia.link/95pzrui8Syb",
        jumlahDriver: 1,
        tipeDriver: "Dynamic",
    },
    {
        id: "13",
        name: "Moondrop SSP",
        price: "600000",
        bass: 4,
        mid: 2,
        treble: 3,
        linkBeli: "https://tokopedia.link/2OpExZk8Syb",
        jumlahDriver: 1,
        tipeDriver: "Dynamic",
    },
    {
        id: "14",
        name: "Moondrop S8",
        price: "9500000",
        bass: 4,
        mid: 3,
        treble: 3,
        linkBeli: "https://tokopedia.link/Q9yqmlm8Syb",
        jumlahDriver: 8,
        tipeDriver: "Balance Armature",
    },
    
    // FiiO
    {
        id: "15",
        name: "FiiO FH3",
        price: "1750000",
        bass: 4,
        mid: 3,
        treble: 2,
        linkBeli: "https://tokopedia.link/xuzNKOmlBzb",
        jumlahDriver: 3,
        tipeDriver: "Hybrid",
    },
    {
        id: "16",
        name: "FiiO FD3",
        price: "1305000",
        bass: 5,
        mid: 2,
        treble: 3,
        linkBeli: "https://tokopedia.link/vNhLdIqlBzb",
        jumlahDriver: 1,
        tipeDriver: "Dynamic",
    },
    
    // 7hz
    {
        id: "17",
        name: "7hz Salnotes Zero",
        price: "235000",
        bass: 3,
        mid: 4,
        treble: 4,
        linkBeli: "https://tokopedia.link/QEA2BUwlBzb",
        jumlahDriver: 1,
        tipeDriver: "Dynamic",
    },
    {
        id: "18",
        name: "7hz Timeless",
        price: "2599000",
        bass: 4,
        mid: 3,
        treble: 5,
        linkBeli: "https://tokopedia.link/BniZJWBlBzb",
        jumlahDriver: 1,
        tipeDriver: "Planar",
    },
    {
        id: "19",
        name: "7hz Dioko",
        price: "1116250",
        bass: 2,
        mid: 3,
        treble: 5,
        linkBeli: "https://tokopedia.link/Or64csIlBzb",
        jumlahDriver: 1,
        tipeDriver: "Planar",
    },
    
    // CCA
    {
        id: "20",
        name: "CCA CRA",
        price: "115000",
        bass: 5,
        mid: 2,
        treble: 4,
        linkBeli: "https://tokopedia.link/ZQgLo2PlBzb",
        jumlahDriver: 1,
        tipeDriver: "Dynamic",
    },
    {
        id: "21",
        name: "CCA CRA+",
        price: "189000",
        bass: 4,
        mid: 2,
        treble: 4,
        linkBeli: "https://tokopedia.link/P6pcMhZlBzb",
        jumlahDriver: 1,
        tipeDriver: "Dynamic",
    },
    
    // HZSound
    {
        id: "22",
        name: "HZSound Heart Mirror",
        price: "685000",
        bass: 2,
        mid: 3,
        treble: 4,
        linkBeli: "https://tokopedia.link/pjAAixamBzb",
        jumlahDriver: 1,
        tipeDriver: "Dynamic",
    },
    
    // Tanchjim
    {
        id: "23",
        name: "Tanchjim Tanya",
        price: "195000",
        bass: 4,
        mid: 2,
        treble: 3,
        linkBeli: "https://tokopedia.link/wT9pjyKdDzb",
        jumlahDriver: 1,
        tipeDriver: "Dynamic",
    },
    {
        id: "24",
        name: "Tanchjim Ola",
        price: "540000",
        bass: 2,
        mid: 4,
        treble: 3,
        linkBeli: "https://tokopedia.link/H5s8YdOdDzb",
        jumlahDriver: 1,
        tipeDriver: "Dynamic",
    },
    {
        id: "25",
        name: "Tanchjim Oxygen",
        price: "3350000",
        bass: 4,
        mid: 3,
        treble: 3,
        linkBeli: "https://tokopedia.link/aoLnnPSdDzb",
        jumlahDriver: 1,
        tipeDriver: "Dynamic",
    },
    {
        id: "26",
        name: "Tanchjim Hana",
        price: "2499000",
        bass: 3,
        mid: 4,
        treble: 3,
        linkBeli: "https://tokopedia.link/ekGzJE7dDzb",
        jumlahDriver: 1,
        tipeDriver: "Dynamic",
    },
    {
        id: "27",
        name: "Tanchjim Zero",
        price: "195000",
        bass: 3,
        mid: 3,
        treble: 4,
        linkBeli: "https://tokopedia.link/V8tsZ9beDzb",
        jumlahDriver: 1,
        tipeDriver: "Dynamic",
    },
    
    // Tin Hifi
    {
        id: "28",
        name: "Tin T2",
        price: "450000",
        bass: 2,
        mid: 2,
        treble: 5,
        linkBeli: "https://tokopedia.link/FEb0f8XlDzb",
        jumlahDriver: 2,
        tipeDriver: "Dynamic",
    },
    {
        id: "29",
        name: "Tin T2 Plus",
        price: "610000",
        bass: 3,
        mid: 3,
        treble: 4,
        linkBeli: "https://tokopedia.link/7tEewt2lDzb",
        jumlahDriver: 1,
        tipeDriver: "Dynamic",
    },
    {
        id: "30",
        name: "Tin T3",
        price: "725000",
        bass: 2,
        mid: 2,
        treble: 4,
        linkBeli: "https://tokopedia.link/wfQY8i7lDzb",
        jumlahDriver: 2,
        tipeDriver: "Hybrid",
    },
    {
        id: "31",
        name: "Tin P1",
        price: "1700000",
        bass: 2,
        mid: 4,
        treble: 4,
        linkBeli: "https://tokopedia.link/C32YBQsmDzb",
        jumlahDriver: 1,
        tipeDriver: "Planar",
    },
    {
        id: "32",
        name: "Tin T4",
        price: "1020000",
        bass: 4,
        mid: 3,
        treble: 4,
        linkBeli: "https://tokopedia.link/YFKwhmemDzb",
        jumlahDriver: 2,
        tipeDriver: "Hybrid",
    },
    {
        id: "33",
        name: "Tin C2 Mech Warrior",
        price: "349000",
        bass: 4,
        mid: 3,
        treble: 3,
        linkBeli: "https://tokopedia.link/44FXyximDzb",
        jumlahDriver: 1,
        tipeDriver: "Dynamic",
    },
    
    // Blon
    {
        id: "34",
        name: "Blon BL03",
        price: "299000",
        bass: 5,
        mid: 3,
        treble: 4,
        linkBeli: "https://tokopedia.link/M77QxyxmDzb",
        jumlahDriver: 1,
        tipeDriver: "Dynamic",
    },
    
    // Tripowin
    {
        id: "35",
        name: "Tripowin Lea",
        price: "270000",
        bass: 3,
        mid: 4,
        treble: 3,
        linkBeli: "https://tokopedia.link/objohGEmDzb",
        jumlahDriver: 1,
        tipeDriver: "Dynamic",
    },
    {
        id: "36",
        name: "Tripowin Mele",
        price: "699000",
        bass: 5,
        mid: 3,
        treble: 3,
        linkBeli: "https://tokopedia.link/HtTRedJmDzb",
        jumlahDriver: 1,
        tipeDriver: "Dynamic",
    },
]